<a href="https://colab.research.google.com/github/sairatabassum/FreeCodeCamp-Pandas-Real-Life-Example/blob/master/Load_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
sales = pd.read_csv(
    'https://raw.githubusercontent.com/ine-rmotr-curriculum/FreeCodeCamp-Pandas-Real-Life-Example/master/data/sales_data.csv')

sales.head(5)

         Date  Day     Month  Year  ...  Unit_Price Profit  Cost Revenue
0  2013-11-26   26  November  2013  ...         120    590   360     950
1  2015-11-26   26  November  2015  ...         120    590   360     950
2  2014-03-23   23     March  2014  ...         120   1366  1035    2401
3  2016-03-23   23     March  2016  ...         120   1188   900    2088
4  2014-05-15   15       May  2014  ...         120    238   180     418

[5 rows x 18 columns]